
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: yarn install
  displayName: 'Install dependencies'

- script: |
    yarn lint
    yarn spellcheck
    find . -not -path './**/node_modules/*' -name "*.md" | xargs docker run --rm --read-only -v $PWD:/data robertbeal/markdown-link-checker
  displayName: 'Lint Markdown'

